### ISSUE TITLE
add action to ensure that workflows are up to date.

### ISSUE THREAD

**Issue by AlexAxthelm** [RMI-PACTA/demo_actions#6]

**Comment by jdhoffa** [comment]
Can you elaborate on this one?

**Comment by AlexAxthelm** [comment]
The basic idea here is that the workflow would check the SHA of the _actions_ repo that is used as a reference in the _content_ repo, and compare to the latest releases (and `main`), to inform if there's a newer version of the actions that have been published. Probably a good candidate for inclusion in housekeeping (#15)

example:
```yaml
#content-repo/.github/workflows/R-Package.yaml
jobs:
  R-package:
    name: R Package Checks
    uses: RMI-PACTA/demo_actions/.github/workflows/R-package.yml@v0.0.3
```
happens to refer to [`fe365f3`](https://github.com/RMI-PACTA/demo_actions/releases/tag/v0.0.3)

when we tag `0.0.4`, this action would raise a little note that says something like "Hey, FYI, there's an updated release of demo_actions available. You might want to consider updating your workflow files to that"

and in the `housekeeping.yml` file, there could be an option to not run this action, in case you want to keep those pinned, similar to the flags I've defined for the Docker actions: https://github.com/RMI-PACTA/demo_actions/blob/fe365f3931c469696d1c01791f26c9674e3abe68/.github/workflows/docker.yml#L20-L24
